name: MarketPlace CI - Java 8 with Kotlin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Install spigot nms dependencies
        run: bash ./install-dependency-in-cache.sh ${{ secrets.CI_URL }} ${{ secrets.CI_USER }} ${{ secrets.CI_PASSWORD }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle - Compile plugin with 1.12.2
        run: ./gradlew clean build -x test -PbuildVersion=1.12.2
      - name: Build with Gradle - Compile plugin with 1.13.2
        run: ./gradlew clean build -x test -PbuildVersion=1.13.2
      - name: Build with Gradle - Compile plugin with 1.14.4
        run: ./gradlew clean build -x test -PbuildVersion=1.14.4
      - name: Build with Gradle - Compile plugin with 1.15.2
        run: ./gradlew clean build -x test -PbuildVersion=1.15.2
      - name: Build with Gradle - Compile plugin with 1.16.5
        run: ./gradlew clean build -x test -PbuildVersion=1.16.5


      - name: List files in build/libs
        run: ls -la build/libs

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar  # Update this path as needed
